Fix invalid-period-type bug (analyzer list), ...
PagesController: analyzers_from_mas_session: Added missing
checks/logging of server errors.  This prevents a bug in which the
error: "Invalid period type: hourly" was being displayed among the
list of 'signal types' (AKA analyzers).

ApplicationController: Added documentation for method
'do_mas_request'.

Also, removed some old, obsolete code.